  export const optionsKnowledge_area = [
    {
      value: "Ciencias Sociales y Jurídicas",
      label: "Ciencias Sociales y Jurídicas",
    },
    { value: "Ingeniería y Tecnología", label: "Ingeniería y Tecnología" },
    { value: "Administración y Gestión", label: "Administración y Gestión" },
    { value: "Ciencias de la Salud", label: "Ciencias de la Salud" },
    {
      value: "Informática y Comunicaciones",
      label: "Informática y Comunicaciones",
    },
    { value: "Ciencias Naturales", label: "Ciencias Naturales" },
    { value: "Servicios y Turismo", label: "Servicios y Turismo" },
    { value: "Artes y Humanidades", label: "Artes y Humanidades" },
    {
      value: "Medio Ambiente y Agroalimentario",
      label: "Medio Ambiente y Agroalimentario",
    },
    { value: "Educación y Formación", label: "Educación y Formación" },
  ];

  export   const optionsType = [
    { value: "Grado", label: "Grado" },
    { value: "Máster", label: "Máster" },
    { value: "FP Básica", label: "FP Básica" },
    { value: "FP Media", label: "FP Media" },
    { value: "FP Superior", label: "FP Superior" },
  ];

export const optionsLocations = [
  { value: "Albacete", label: "Albacete" },
  { value: "Alicante", label: "Alicante" },
  { value: "Almería", label: "Almería" },
  { value: "Álava", label: "Álava" },
  { value: "Asturias", label: "Asturias" },
  { value: "Ávila", label: "Ávila" },
  { value: "Badajoz", label: "Badajoz" },
  { value: "Barcelona", label: "Barcelona" },
  { value: "Burgos", label: "Burgos" },
  { value: "Cáceres", label: "Cáceres" },
  { value: "Cádiz", label: "Cádiz" },
  { value: "Cantabria", label: "Cantabria" },
  { value: "Castellón", label: "Castellón" },
  { value: "Ciudad Real", label: "Ciudad Real" },
  { value: "Córdoba", label: "Córdoba" },
  { value: "Cuenca", label: "Cuenca" },
  { value: "Gerona", label: "Gerona" },
  { value: "Granada", label: "Granada" },
  { value: "Guadalajara", label: "Guadalajara" },
  { value: "Guipúzcoa", label: "Guipúzcoa" },
  { value: "Huelva", label: "Huelva" },
  { value: "Huesca", label: "Huesca" },
  { value: "Islas Baleares", label: "Islas Baleares" },
  { value: "Jaén", label: "Jaén" },
  { value: "La Coruña", label: "La Coruña" },
  { value: "La Rioja", label: "La Rioja" },
  { value: "Las Palmas", label: "Las Palmas" },
  { value: "León", label: "León" },
  { value: "Lérida", label: "Lérida" },
  { value: "Lugo", label: "Lugo" },
  { value: "Madrid", label: "Madrid" },
  { value: "Málaga", label: "Málaga" },
  { value: "Murcia", label: "Murcia" },
  { value: "Navarra", label: "Navarra" },
  { value: "Orense", label: "Orense" },
  { value: "Palencia", label: "Palencia" },
  { value: "Pontevedra", label: "Pontevedra" },
  { value: "Salamanca", label: "Salamanca" },
  { value: "Santa Cruz de Tenerife", label: "Santa Cruz de Tenerife" },
  { value: "Segovia", label: "Segovia" },
  { value: "Sevilla", label: "Sevilla" },
  { value: "Soria", label: "Soria" },
  { value: "Teruel", label: "Teruel" },
  { value: "Toledo", label: "Toledo" },
  { value: "Valencia", label: "Valencia" },
  { value: "Valladolid", label: "Valladolid" },
  { value: "Vizcaya", label: "Vizcaya" },
  { value: "Zamora", label: "Zamora" },
  { value: "Zaragoza", label: "Zaragoza" }
];
